export 'advertise/advertise.dart';
export 'home/home.dart';
export 'register/register.dart';
export 'splash/splash.dart';
export 'shopping/shopping.dart';
export 'detail/detail.dart';
export 'zoom/zoom.dart';
export 'cart/cart.dart';
export 'confirm/confirm.dart';